// This file will be auto-generated by Supabase CLI
// Run: npm run db:generate-types

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[]

export interface Database {
  public: {
    Tables: {
      activities: {
        Row: {
          id: string
          goal_id: string | null
          title: string
          icon_name: string
          activity_type: string | null
          data: Json | null
          created_at: string | null
        }
        Insert: {
          id?: string
          goal_id?: string | null
          title: string
          icon_name: string
          activity_type?: string | null
          data?: Json | null
          created_at?: string | null
        }
        Update: {
          id?: string
          goal_id?: string | null
          title?: string
          icon_name?: string
          activity_type?: string | null
          data?: Json | null
          created_at?: string | null
        }
      }
      goals: {
        Row: {
          id: string
          name: string
          milestone_description: string
          start_date: string
          milestone_date: string
          reason: string | null
          image_system_name: string | null
          is_manually_completed: boolean
          progress_data: Json | null
          created_at: string
        }
        Insert: {
          id?: string
          name: string
          milestone_description: string
          start_date: string
          milestone_date: string
          reason?: string | null
          image_system_name?: string | null
          is_manually_completed?: boolean
          progress_data?: Json | null
          created_at?: string
        }
        Update: {
          id?: string
          name?: string
          milestone_description?: string
          start_date?: string
          milestone_date?: string
          reason?: string | null
          image_system_name?: string | null
          is_manually_completed?: boolean
          progress_data?: Json | null
          created_at?: string
        }
      }
      daily_nutrition_est: {
        Row: {
          day_est: string
          calories_kcal: number
          protein_g: number
          carbs_g: number
          fat_g: number
        }
        Insert: {
          day_est: string
          calories_kcal: number
          protein_g: number
          carbs_g: number
          fat_g: number
        }
        Update: {
          day_est?: string
          calories_kcal?: number
          protein_g?: number
          carbs_g?: number
          fat_g?: number
        }
      }
      nutrition_entries: {
        Row: {
          id: string
          start_at: string
          end_at: string
          kind: string
          value: number
          unit: string
          source: string
          sample_uuid: string | null
          created_at: string
        }
        Insert: {
          id?: string
          start_at: string
          end_at: string
          kind: string
          value: number
          unit: string
          source?: string
          sample_uuid?: string | null
          created_at?: string
        }
        Update: {
          id?: string
          start_at?: string
          end_at?: string
          kind?: string
          value?: number
          unit?: string
          source?: string
          sample_uuid?: string | null
          created_at?: string
        }
      }
    }
    Views: {
      [_ in never]: never
    }
    Functions: {
      [_ in never]: never
    }
    Enums: {
      [_ in never]: never
    }
  }
}

